### ISSUE TITLE
Crash on incorrect key

### ISSUE THREAD

**Issue by this-self** [laggingreflex/socket.io-encrypt#2]
If the other side will send the message which cannot be decrypted, then the server will be crashed due to unable to parse json string which hasn't been decrypted correctly.

**Comment by laggingreflex** [comment]
Fixed, released v0.1.1. 

Use `socket.on('error')` to handle such errors. See [example](https://github.com/laggingreflex/socket.io-encrypt/blob/master/example/server.js#L20)

Thanks for reporting!
