### ISSUE TITLE
i got "secret is not define" in server.js, where am i wrong?

### ISSUE THREAD

**Issue by huytrv** [laggingreflex/socket.io-encrypt#6]

**Comment by laggingreflex** [comment]
Are you copy-pasting code straight from the example? Did you define the variable `secret`?

**Comment by huytrv** [comment]
can you explain what is secret variable and how to declare?

**Comment by laggingreflex** [comment]
You haven't provided your code so I'm only assuming you've copied the code from the examples. 

```
const SocketIO = require('socket.io')
const encrypt = require('socket.io-encrypt')

const io = SocketIO({})
io.use(encrypt(secret)) // << and this is where the error is, I presume?
```

in which case simply define the variable. 

```
const secret = 'your secret'
io.use(encrypt(secret))
```

Hope that solves it. 

http://stacstackoverflow.com is a great resource for general questions.

**Comment by huytrv** [comment]
secret variable only get custom value? Thanks for help

Vào Th 7, 27 thg 6, 2020 vào lúc 12:01 laggingreflex <
notifications@github.com> đã viết:

**Comment by laggingreflex** [comment]
Yes, it has to be a custom value set by you. That's why it's called a "secret". It'll be used as a key to encrypt and decrypt all the messages.

**Comment by huytrv** [comment]
so how should the secret be set to ensure confidentiality and how I can
check its security?🤔

Vào Th 7, 27 thg 6, 2020 vào lúc 17:13 laggingreflex <
notifications@github.com> đã viết:

**Comment by laggingreflex** [comment]
That's too broad a question for me to answer authoritatively I'm afraid. Neither is it specific to this library. You may be better off researching it as a general topic.
